### ISSUE TITLE
gulp command not working

### ISSUE THREAD

**Issue by AnouckF** [estruyf/Search-WP-SPFx#5]
When I'm running any gulp command like gulp serve, gulp build I receive the following issue. 

 gulp serve
Build target: DEBUG
C:\_dev\Search-WP-SPFx\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178
            throw new Error(prefix + os.EOL +
            ^

Error: JSON validation failed:
C:\_dev\Search-WP-SPFx\config\tslint.json

Error: #/ (Defines configuration options for the...)
       Additional properties not allowed: lintConfig,useDefaultConfigAsBase,removeExistingRules,displayAsWarning
    at validateObjectWithCallback (C:\_dev\Search-WP-SPFx\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:178:19)
    at JsonSchema.validateObjectWithCallback (C:\_dev\Search-WP-SPFx\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:193:13)
    at JsonSchema.validateObject (C:\_dev\Search-WP-SPFx\node_modules\@microsoft\node-core-library\lib\JsonSchema.js:175:14)
    at TslintCmdTask._readConfigFile (C:\_dev\Search-WP-SPFx\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:311:28)
    at TslintCmdTask.onRegister (C:\_dev\Search-WP-SPFx\node_modules\@microsoft\gulp-core-build\lib\tasks\GulpTask.js:87:32)
    at Object.initialize (C:\_dev\Search-WP-SPFx\node_modules\@microsoft\gulp-core-build\lib\index.js:299:24)
    at SPWebBuildRig.initialize (C:\_dev\Search-WP-SPFx\node_modules\@microsoft\sp-build-common\lib\BuildRig.js:61:19)
    at SPWebBuildRig.initialize (C:\_dev\Search-WP-SPFx\node_modules\@microsoft\sp-build-common\lib\SPBuildRig.js:28:15)
    at Object.exports.initialize (C:\_dev\Search-WP-SPFx\node_modules\@microsoft\sp-build-web\lib\index.js:22:17)
    at Object.<anonymous> (C:\_dev\Search-WP-SPFx\gulpfile.js:6:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
PS C:\_dev\Search-WP-SPFx>

I have cloned the solution,
run npm install 
and try gulp serve

Is there is fix for this problem?

I tried this whit a solution I have created and there is not problem with thate one.

**Comment by estruyf** [comment]
Seems to be something is wrong with the dependencies which got installed, what version of Node are you using? The project itself was created with v1, so at that time it only supported node v6.

PS: I would recommend using this version: https://github.com/estruyf/react-handlebars-search - best to try this one.

**Comment by AnouckF** [comment]
Thanks for the feedback. 
I'm running nvm for multiple node versions. i have installed version 6.17.1 and it is working.
